<?php
/**
 * Тексты страницы «Конструкция и материалы» на трёх языках.
 * Возвращает массив для текущего языка.
 *
 * @package rowkz
 */

$rk_construction = array();

$rk_construction['ru'] = array(
	'eyebrow' => 'Лодки · Конструкция',
	'title'   => 'Конструкция и материалы гоночных лодок',
	'lead'    => 'Корпуса Swift — это сэндвич-конструкция на эпоксидной смоле, отверждённая под вакуумом при нагреве. Несколько классов исполнения позволяют подобрать лодку под задачу и бюджет.',
	'grades_kicker' => 'Классы исполнения',
	'grades_title'  => 'Из чего сделана лодка',
	'grades_lead'   => 'Классы отличаются материалами, весом и ценой. Нажмите на класс, чтобы увидеть состав.',
	'img_alt'       => 'Материалы конструкции гоночной лодки',
	'labels'  => array( 'hull' => 'Корпус', 'sides' => 'Борта', 'decks' => 'Палубы и сиденье', 'for' => 'Для кого' ),
	'grades'  => array(
		array( 'key' => 'cpro', 'name' => 'Carbon Pro', 'tag' => 'С 2023 года · Премиум', 'for' => 'Когда важна каждая секунда: максимальный результат на соревнованиях.',
			'hull'  => array( 'Сотовая сердцевина', 'Внутренний и внешний слой — препрег углерод', 'Армирование — препрег углерод' ),
			'sides' => array( 'Как у корпуса: соты и препрег углерод' ),
			'decks' => array( 'Сотовая сердцевина', 'Внутренний и внешний слой — препрег углерод' ) ),
		array( 'key' => 'ec', 'name' => 'Elite Carbon', 'tag' => 'Элита', 'for' => 'Соревнования самого высокого уровня.',
			'hull'  => array( 'Сотовая сердцевина', 'Внутренний и внешний слой — углерод', 'Армирование — углерод' ),
			'sides' => array( 'Как у корпуса: соты и углерод' ),
			'decks' => array( 'Палубы: соты, углерод внутри и снаружи', 'Сиденье: пена ПВХ с закрытыми ячейками и углеродом' ) ),
		array( 'key' => 'ep', 'name' => 'Elite Plus', 'tag' => 'Профессиональный', 'for' => 'Соревнования высокого уровня.',
			'hull'  => array( 'Сотовая сердцевина', 'Внутри — препрег углерод (2-, 4-, 8-местные) / углерод (1x)', 'Снаружи — препрег кевлар-углерод (2-, 4-, 8-местные) / углерод (1x)', 'Армирование — препрег углерод' ),
			'sides' => array( 'Сотовая сердцевина', 'Внутри — препрег углерод, снаружи — препрег кевлар-углерод' ),
			'decks' => array( 'Палубы: соты и препрег углерод', 'Сиденье: пена ПВХ с закрытыми ячейками' ) ),
		array( 'key' => 'ca', 'name' => 'Club A', 'tag' => 'Клубный', 'for' => 'Тренировки с возможностью выступать на соревнованиях. Тяжелее Elite Plus примерно на 2 кг (1x).',
			'hull'  => array( 'Сердцевина Coremat', 'Внутри — углерод, снаружи — кевлар', 'Армирование — углерод' ),
			'sides' => array( '2-, 4-, 8-местные: сотовая сердцевина', '1x: пена ПВХ с закрытыми ячейками', 'Слои углерода и кевлара' ),
			'decks' => array( 'Палубы: соты со стекловолокном', 'Сиденье: пена ПВХ с кевларом и углеродом' ) ),
		array( 'key' => 'cb', 'name' => 'Club B', 'tag' => 'Тренировочный', 'for' => 'Ежедневные тренировки: надёжная «рабочая лошадка», немного тяжелее и легко ремонтируется.',
			'hull'  => array( 'Сердцевина Coremat', 'Слои стекловолокна' ),
			'sides' => array( '2-, 4-, 8-местные: сотовая сердцевина', '1x: пена с закрытыми ячейками', 'Стекловолокно, армирование углеродом' ),
			'decks' => array( 'Палубы: соты со стекловолокном', 'Сиденье: пена ПВХ со стекловолокном' ) ),
	),
	'weight_kicker' => 'Вес',
	'weight_title'  => 'Вес лодок',
	'weight' => array(
		array( 'Carbon Pro', array( 'С карбоновыми риггерами — на уровне минимума World Rowing или ниже', 'С алюминиевыми риггерами — на уровне минимума или ниже (1x — до 14,3 кг)' ) ),
		array( 'Elite Carbon и Elite Plus', array( 'На уровне минимального веса World Rowing или близко к нему' ) ),
		array( 'Club A — тяжелее Elite Plus', array( '1x: +2 кг', '2x: +2,5 кг', '4x: +4 кг', '8+: +8 кг' ) ),
		array( 'Club B — тяжелее Club A', array( '1x: +1,5 кг', '2x: +1,5 кг', '4x: +3 кг' ) ),
	),
	'weight_note' => 'Вес указан приблизительно. Точные данные по конкретной модели — у нашего менеджера.',
	'about_kicker' => 'Технология',
	'about_title'  => 'Как устроен корпус',
	'about_lead'   => 'Сэндвич — это два слоя ткани (углерод, кевлар или стекловолокно) и лёгкая сердцевина между ними. Слои пропитываются смолой и запекаются под вакуумом — так получается жёсткая и лёгкая лодка.',
	'cores' => array(
		array( 'bi-hexagon', 'Сотовая сердцевина', 'Самая лёгкая. Используется в гоночных классах, где важен каждый грамм.' ),
		array( 'bi-layers', 'Coremat', 'Прочнее и проще в ремонте. Выбор для клубных лодок, где важнее долговечность и цена.' ),
	),
	'cta_title' => 'Не знаете, какой класс выбрать?',
	'cta_text'  => 'Расскажите, кто будет грести и как часто, — подберём класс и модель.',
	'cta_btn'   => 'Получить консультацию',
	'cta_btn2'  => 'Гоночные лодки',
);

$rk_construction['en'] = array(
	'eyebrow' => 'Boats · Construction',
	'title'   => 'Racing boat construction and materials',
	'lead'    => 'Swift hulls use an epoxy sandwich layup cured under vacuum with heat. Several build grades let you match the boat to your goals and budget.',
	'grades_kicker' => 'Build grades',
	'grades_title'  => 'What the boat is made of',
	'grades_lead'   => 'Grades differ in materials, weight and price. Select a grade to see its layup.',
	'img_alt'       => 'Racing boat construction materials',
	'labels'  => array( 'hull' => 'Hull', 'sides' => 'Sides', 'decks' => 'Decks and seat', 'for' => 'Best for' ),
	'grades'  => array(
		array( 'key' => 'cpro', 'name' => 'Carbon Pro', 'tag' => 'Since 2023 · Premium', 'for' => 'When every second counts: top racing results.',
			'hull'  => array( 'Honeycomb core', 'Inner and outer skins: prepreg carbon', 'Reinforcement: prepreg carbon' ),
			'sides' => array( 'Same as hull: honeycomb and prepreg carbon' ),
			'decks' => array( 'Honeycomb core', 'Inner and outer skins: prepreg carbon' ) ),
		array( 'key' => 'ec', 'name' => 'Elite Carbon', 'tag' => 'Elite', 'for' => 'Racing at the highest level.',
			'hull'  => array( 'Honeycomb core', 'Inner and outer skins: carbon', 'Reinforcement: carbon' ),
			'sides' => array( 'Same as hull: honeycomb and carbon' ),
			'decks' => array( 'Decks: honeycomb, carbon on both sides', 'Seat: closed-cell PVC foam with carbon' ) ),
		array( 'key' => 'ep', 'name' => 'Elite Plus', 'tag' => 'Professional', 'for' => 'High-level racing.',
			'hull'  => array( 'Honeycomb core', 'Inner: prepreg carbon (2-, 4-, 8-seat) / carbon (1x)', 'Outer: prepreg Kevlar-carbon (2-, 4-, 8-seat) / carbon (1x)', 'Reinforcement: prepreg carbon' ),
			'sides' => array( 'Honeycomb core', 'Inner prepreg carbon, outer prepreg Kevlar-carbon' ),
			'decks' => array( 'Decks: honeycomb and prepreg carbon', 'Seat: closed-cell PVC foam' ) ),
		array( 'key' => 'ca', 'name' => 'Club A', 'tag' => 'Club', 'for' => 'Training with the option to race. About 2 kg heavier than Elite Plus (1x).',
			'hull'  => array( 'Coremat core', 'Inner carbon, outer Kevlar', 'Reinforcement: carbon' ),
			'sides' => array( '2-, 4-, 8-seat: honeycomb core', '1x: closed-cell PVC foam', 'Carbon and Kevlar skins' ),
			'decks' => array( 'Decks: honeycomb with fibreglass', 'Seat: PVC foam with Kevlar and carbon' ) ),
		array( 'key' => 'cb', 'name' => 'Club B', 'tag' => 'Training', 'for' => 'Everyday training: a dependable workhorse, a little heavier and easy to repair.',
			'hull'  => array( 'Coremat core', 'Fibreglass skins' ),
			'sides' => array( '2-, 4-, 8-seat: honeycomb core', '1x: closed-cell foam', 'Fibreglass with carbon reinforcement' ),
			'decks' => array( 'Decks: honeycomb with fibreglass', 'Seat: PVC foam with fibreglass' ) ),
	),
	'weight_kicker' => 'Weight',
	'weight_title'  => 'Boat weight',
	'weight' => array(
		array( 'Carbon Pro', array( 'Carbon riggers: at or below the World Rowing minimum', 'Aluminium riggers: at or below the minimum (1x up to 14.3 kg)' ) ),
		array( 'Elite Carbon and Elite Plus', array( 'At or close to the World Rowing minimum weight' ) ),
		array( 'Club A vs Elite Plus', array( '1x: +2 kg', '2x: +2.5 kg', '4x: +4 kg', '8+: +8 kg' ) ),
		array( 'Club B vs Club A', array( '1x: +1.5 kg', '2x: +1.5 kg', '4x: +3 kg' ) ),
	),
	'weight_note' => 'Weights are approximate. Ask our manager for exact figures for a specific model.',
	'about_kicker' => 'Technology',
	'about_title'  => 'How the hull is built',
	'about_lead'   => 'A sandwich is two fabric skins (carbon, Kevlar or fibreglass) with a light core in between. The layers are wetted with resin and cured under vacuum, which makes the boat stiff and light.',
	'cores' => array(
		array( 'bi-hexagon', 'Honeycomb core', 'The lightest option, used in racing grades where every gram matters.' ),
		array( 'bi-layers', 'Coremat', 'Tougher and easier to repair. The choice for club boats, where durability and price matter more.' ),
	),
	'cta_title' => 'Not sure which grade to choose?',
	'cta_text'  => 'Tell us who will row and how often, and we will suggest a grade and model.',
	'cta_btn'   => 'Get advice',
	'cta_btn2'  => 'Racing boats',
);

$rk_construction['kk'] = array(
	'eyebrow' => 'Қайықтар · Құрылымы',
	'title'   => 'Жарыс қайықтарының құрылымы мен материалдары',
	'lead'    => 'Swift корпустары — эпоксидті шайырдағы сэндвич-құрылым, вакуумда қыздырылып қатырылады. Бірнеше орындау класы қайықты мақсат пен бюджетке сай таңдауға мүмкіндік береді.',
	'grades_kicker' => 'Орындау кластары',
	'grades_title'  => 'Қайық неден жасалған',
	'grades_lead'   => 'Кластар материалы, салмағы және бағасы бойынша ерекшеленеді. Құрамын көру үшін класты таңдаңыз.',
	'img_alt'       => 'Жарыс қайығы құрылымының материалдары',
	'labels'  => array( 'hull' => 'Корпус', 'sides' => 'Бүйірлері', 'decks' => 'Палуба және отырғыш', 'for' => 'Кімге арналған' ),
	'grades'  => array(
		array( 'key' => 'cpro', 'name' => 'Carbon Pro', 'tag' => '2023 жылдан · Премиум', 'for' => 'Әр секунд маңызды болғанда: жарыстағы ең жоғары нәтиже.',
			'hull'  => array( 'Ұялы өзек', 'Ішкі және сыртқы қабат — препрег көміртек', 'Арматура — препрег көміртек' ),
			'sides' => array( 'Корпус сияқты: ұялы өзек және препрег көміртек' ),
			'decks' => array( 'Ұялы өзек', 'Ішкі және сыртқы қабат — препрег көміртек' ) ),
		array( 'key' => 'ec', 'name' => 'Elite Carbon', 'tag' => 'Элита', 'for' => 'Ең жоғары деңгейдегі жарыстар.',
			'hull'  => array( 'Ұялы өзек', 'Ішкі және сыртқы қабат — көміртек', 'Арматура — көміртек' ),
			'sides' => array( 'Корпус сияқты: ұялы өзек және көміртек' ),
			'decks' => array( 'Палуба: ұялы өзек, екі жағы көміртек', 'Отырғыш: тұйық ұяшықты ПВХ көбігі және көміртек' ) ),
		array( 'key' => 'ep', 'name' => 'Elite Plus', 'tag' => 'Кәсіби', 'for' => 'Жоғары деңгейдегі жарыстар.',
			'hull'  => array( 'Ұялы өзек', 'Іші — препрег көміртек (2, 4, 8 орындық) / көміртек (1x)', 'Сырты — препрег кевлар-көміртек (2, 4, 8 орындық) / көміртек (1x)', 'Арматура — препрег көміртек' ),
			'sides' => array( 'Ұялы өзек', 'Іші — препрег көміртек, сырты — препрег кевлар-көміртек' ),
			'decks' => array( 'Палуба: ұялы өзек және препрег көміртек', 'Отырғыш: тұйық ұяшықты ПВХ көбігі' ) ),
		array( 'key' => 'ca', 'name' => 'Club A', 'tag' => 'Клубтық', 'for' => 'Жарысқа да шығуға болатын жаттығулар. Elite Plus-тан шамамен 2 кг ауыр (1x).',
			'hull'  => array( 'Coremat өзегі', 'Іші — көміртек, сырты — кевлар', 'Арматура — көміртек' ),
			'sides' => array( '2, 4, 8 орындық: ұялы өзек', '1x: тұйық ұяшықты ПВХ көбігі', 'Көміртек және кевлар қабаттары' ),
			'decks' => array( 'Палуба: шыныталшықты ұялы өзек', 'Отырғыш: кевлар мен көміртекті ПВХ көбігі' ) ),
		array( 'key' => 'cb', 'name' => 'Club B', 'tag' => 'Жаттығу', 'for' => 'Күнделікті жаттығулар: сенімді «жұмысшы ат», сәл ауырлау және жөндеуге оңай.',
			'hull'  => array( 'Coremat өзегі', 'Шыныталшық қабаттары' ),
			'sides' => array( '2, 4, 8 орындық: ұялы өзек', '1x: тұйық ұяшықты көбік', 'Шыныталшық, көміртекпен арматураланған' ),
			'decks' => array( 'Палуба: шыныталшықты ұялы өзек', 'Отырғыш: шыныталшықты ПВХ көбігі' ) ),
	),
	'weight_kicker' => 'Салмақ',
	'weight_title'  => 'Қайықтардың салмағы',
	'weight' => array(
		array( 'Carbon Pro', array( 'Көміртек риггерлерімен — World Rowing минимумы деңгейінде немесе одан төмен', 'Алюминий риггерлерімен — минимум деңгейінде немесе төмен (1x — 14,3 кг-ға дейін)' ) ),
		array( 'Elite Carbon және Elite Plus', array( 'World Rowing минималды салмағы деңгейінде немесе оған жақын' ) ),
		array( 'Club A — Elite Plus-пен салыстырғанда', array( '1x: +2 кг', '2x: +2,5 кг', '4x: +4 кг', '8+: +8 кг' ) ),
		array( 'Club B — Club A-мен салыстырғанда', array( '1x: +1,5 кг', '2x: +1,5 кг', '4x: +3 кг' ) ),
	),
	'weight_note' => 'Салмақ шамамен көрсетілген. Нақты модель бойынша дәл деректерді менеджерімізден сұраңыз.',
	'about_kicker' => 'Технология',
	'about_title'  => 'Корпус қалай жасалады',
	'about_lead'   => 'Сэндвич — екі мата қабаты (көміртек, кевлар немесе шыныталшық) және олардың арасындағы жеңіл өзек. Қабаттар шайырмен сіңіріліп, вакуумда пісіріледі — нәтижесінде қатты әрі жеңіл қайық шығады.',
	'cores' => array(
		array( 'bi-hexagon', 'Ұялы өзек', 'Ең жеңіл нұсқа. Әр грамм маңызды жарыс кластарында қолданылады.' ),
		array( 'bi-layers', 'Coremat', 'Берік әрі жөндеуге оңай. Ұзақ қызмет пен баға маңыздырақ клубтық қайықтарға арналған.' ),
	),
	'cta_title' => 'Қай класты таңдау керек екенін білмейсіз бе?',
	'cta_text'  => 'Кім және қаншалықты жиі есетінін айтыңыз — класс пен модельді таңдап береміз.',
	'cta_btn'   => 'Кеңес алу',
	'cta_btn2'  => 'Жарыс қайықтары',
);

$rk_lang = function_exists( 'rowkz_lang' ) ? rowkz_lang() : 'ru';
return isset( $rk_construction[ $rk_lang ] ) ? $rk_construction[ $rk_lang ] : $rk_construction['ru'];
